--- !ruby/object:VR_ENV
vr_yaml_file: C:/D_Drive_Stuff/Prakher/5_Prakher_Projects/23_VRProjects/coinflip/.vr_settings.yaml
width: 1860
height: 949
panel_pos: 439
notebook_panel_position: 639
run_command_line: ruby coinflip.rb
open_files:
- C:/D_Drive_Stuff/Prakher/5_Prakher_Projects/23_VRProjects/coinflip/src/MyClass.rb
- C:/D_Drive_Stuff/Prakher/5_Prakher_Projects/23_VRProjects/coinflip/coinflip.gemspec
open_folders:
- C:/D_Drive_Stuff/Prakher/5_Prakher_Projects/23_VRProjects/coinflip
- C:/D_Drive_Stuff/Prakher/5_Prakher_Projects/23_VRProjects/coinflip/src
current_file: C:/D_Drive_Stuff/Prakher/5_Prakher_Projects/23_VRProjects/coinflip/coinflip.gemspec
current_line: 19
rdoc_command_line: rdoc -x README
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
